

version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: bank_postgres_db
    environment:
      POSTGRES_DB: bank_card_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge
